[package]
name = "ncku-thesis-typst"
version = "0.0.0"
entrypoint = "lib.typ"
authors = ["Haouo"]
license = "MIT"
description = "NCKU Thesis template in typst"
repository = "https://github.com/Haouo/NCKU-Thesis-Typst"
keywords = ["NCKU", "thesis"]
categories = ["thesis"]
exclude = ["images"]

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "example-thesis.png"
